# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lucas Cherobin\Documents\GitHub\trabalho-api\cotacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\\\Users\\\\Lucas Cherobin\\\\Documents\\\\GitHub\\\\trabalho-api\\\\icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.moedaLabel = QtWidgets.QLabel(Dialog)
        self.moedaLabel.setGeometry(QtCore.QRect(10, 10, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.moedaLabel.setFont(font)
        self.moedaLabel.setObjectName("moedaLabel")
        self.moedaTextEdit = QtWidgets.QTextEdit(Dialog)
        self.moedaTextEdit.setGeometry(QtCore.QRect(10, 30, 191, 31))
        self.moedaTextEdit.setObjectName("moedaTextEdit")
        self.consultacotacao = QtWidgets.QPushButton(Dialog)
        self.consultacotacao.setGeometry(QtCore.QRect(290, 60, 90, 28))
        self.consultacotacao.setObjectName("consultacotacao")
        self.limparcotacao = QtWidgets.QPushButton(Dialog)
        self.limparcotacao.setGeometry(QtCore.QRect(290, 100, 90, 28))
        self.limparcotacao.setObjectName("limparcotacao")
        self.conteudoTextBrowser = QtWidgets.QTextBrowser(Dialog)
        self.conteudoTextBrowser.setGeometry(QtCore.QRect(10, 131, 371, 161))
        self.conteudoTextBrowser.setObjectName("conteudoTextBrowser")
        self.moeda_2Label = QtWidgets.QLabel(Dialog)
        self.moeda_2Label.setGeometry(QtCore.QRect(10, 70, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.moeda_2Label.setFont(font)
        self.moeda_2Label.setObjectName("moeda_2Label")
        self.moeda_2TextEdit = QtWidgets.QTextEdit(Dialog)
        self.moeda_2TextEdit.setGeometry(QtCore.QRect(10, 91, 191, 31))
        self.moeda_2TextEdit.setObjectName("moeda_2TextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cotação"))
        self.moedaLabel.setText(_translate("Dialog", "Código da Moeda Base"))
        self.consultacotacao.setText(_translate("Dialog", "Consultar"))
        self.limparcotacao.setText(_translate("Dialog", "Limpar"))
        self.moeda_2Label.setText(_translate("Dialog", "Código da Segunda Moeda"))
