# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lucas Cherobin\Documents\GitHub\trabalho-api\cotall.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Lucas Cherobin\\Documents\\GitHub\\trabalho-api\\../../../Desktop/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.consultaButton = QtWidgets.QPushButton(Dialog)
        self.consultaButton.setGeometry(QtCore.QRect(10, 10, 381, 31))
        self.consultaButton.setObjectName("consultaButton")
        self.limparButton = QtWidgets.QPushButton(Dialog)
        self.limparButton.setGeometry(QtCore.QRect(800, 60, 90, 28))
        self.limparButton.setObjectName("limparButton")
        self.conteudoTextBrowser = QtWidgets.QTextBrowser(Dialog)
        self.conteudoTextBrowser.setGeometry(QtCore.QRect(10, 61, 381, 231))
        self.conteudoTextBrowser.setObjectName("conteudoTextBrowser")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cotação de Todas Moedas"))
        self.consultaButton.setText(_translate("Dialog", "Consultar"))
        self.limparButton.setText(_translate("Dialog", "Limpar"))
