# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lucas Cherobin\Documents\GitHub\trabalho-api\fechamento.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Lucas Cherobin\\Documents\\GitHub\\trabalho-api\\../../../Desktop/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.moedaLabel = QtWidgets.QLabel(Dialog)
        self.moedaLabel.setGeometry(QtCore.QRect(10, 10, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.moedaLabel.setFont(font)
        self.moedaLabel.setObjectName("moedaLabel")
        self.moedaTextEdit = QtWidgets.QTextEdit(Dialog)
        self.moedaTextEdit.setGeometry(QtCore.QRect(10, 30, 191, 31))
        self.moedaTextEdit.setObjectName("moedaTextEdit")
        self.consultafechamento = QtWidgets.QPushButton(Dialog)
        self.consultafechamento.setGeometry(QtCore.QRect(290, 60, 90, 28))
        self.consultafechamento.setObjectName("consultafechamento")
        self.limparFechamentoButton = QtWidgets.QPushButton(Dialog)
        self.limparFechamentoButton.setGeometry(QtCore.QRect(290, 100, 90, 28))
        self.limparFechamentoButton.setObjectName("limparFechamentoButton")
        self.conteudoTextBrowser = QtWidgets.QTextBrowser(Dialog)
        self.conteudoTextBrowser.setGeometry(QtCore.QRect(10, 131, 371, 161))
        self.conteudoTextBrowser.setObjectName("conteudoTextBrowser")
        self.dayLabel = QtWidgets.QLabel(Dialog)
        self.dayLabel.setGeometry(QtCore.QRect(10, 70, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dayLabel.setFont(font)
        self.dayLabel.setObjectName("dayLabel")
        self.dayTextEdit = QtWidgets.QTextEdit(Dialog)
        self.dayTextEdit.setGeometry(QtCore.QRect(10, 91, 191, 31))
        self.dayTextEdit.setObjectName("dayTextEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Fechamento"))
        self.moedaLabel.setText(_translate("Dialog", "Código da Moeda"))
        self.consultafechamento.setText(_translate("Dialog", "Consultar"))
        self.limparFechamentoButton.setText(_translate("Dialog", "Limpar"))
        self.dayLabel.setText(_translate("Dialog", "Quantia de Dias"))
